### PR TITLE
Remove minimum row length from delimited importers

### PR DESCRIPTION
**Pull request by joshpencheon**
@timgentry, are you aware of the reason behind these clauses? I've had a frustrating hour or so working out why my file wasn't mapping...

### CODE REVIEW

**Comment by timgentry** [comment]
It's a legacy thing. If we get rid of it, and I think we should, we need to communicate to users that import behaviour may change. Presumably it will be a major version bump?

**Comment by joshpencheon** [comment]
True - @ollietulloch, we could presumably scan delimited files to see if it common to receive files with such rows?

We could look at pushing this legacy behaviour back in to the application from which it came, and manage it from there? Would still want to follow SemVer though...

**Comment by timgentry** [comment]
My thinking exactly

**Comment by ollietulloch** [comment]
@joshpencheon, we certainly could scan files. I can discuss with users to identify any potential candidates for further investigation.

**Pull request merged**
